### ISSUE TITLE
Could you mark this as 1.19 supported over on Modrinth?

### ISSUE THREAD

**Issue by intergrav** [Kirilliriks/Bedrodium#7]
It seems to work perfectly fine on 1.19, and would be nice so I can add it to my 1.19 modpack. Thanks!

**Comment by Kirilliriks** [comment]
@intergrav Thanks for the information, it's nice that the modification is able to work on the next version, in the near future I will try to release the version under 1.19 and then I will mark support for 1.19, due to the technical features of Fabric. (In fact, there will be no cardinal changes, you can say I'll just update some points to the current version). Yes, of course, you can use the modification in your modpack, I will be glad about it. As soon as I make a version under 1.19, I will inform you about it here.

**Comment by intergrav** [comment]
Alright, thank you!

**Comment by Kirilliriks** [comment]
> Alright, thank you!

I'm sorry it didn't happen sooner, but I added full support for 1.19.2
